### ISSUE TITLE
[Bug] 按官网示例创建demo项目，报错：SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by SilenceRichard** [ant-design/ant-design-web3#1241]
## Context

- **Ant Design Web3 Version**: ^1.18.0
- **Node Version**: v20.18.0
- **Platform**: 本地开发

## What happens?
按照https://web3.ant.design/course/dev-init-cn 安装依赖，执行npm run dev, 访问 http://localhost:3000/web3 报错

## How To Reproduce

1. 按照官网示例安装项目依赖
2. 配置next.config.js文件
    ```
    /** @type {import('next').NextConfig} */
    const nextConfig = {
      reactStrictMode: true,
      transpilePackages: [
      "@ant-design",
      "antd",
      "rc-util",
      "rc-pagination",
      "rc-picker",
     ],
    };
    // module.exports = nextConfig;
    export default nextConfig;


3. 访问http://localhost:3000/web3, 页面报错
```
export function hasAddon(props) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at rc-input/es/utils/commonUtils (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/pages/web3.js:604:18)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/Input.js:12:87)
    at ./node_modules/antd/es/input/Input.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1040:1)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/TextArea.js:20:64)
    at ./node_modules/antd/es/input/TextArea.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1050:1)
/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/rc-input/es/utils/commonUtils.js:1
export function hasAddon(props) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at rc-input/es/utils/commonUtils (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/pages/web3.js:604:18)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/Input.js:12:87)
    at ./node_modules/antd/es/input/Input.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1040:1)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/TextArea.js:20:64)
    at ./node_modules/antd/es/input/TextArea.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1050:1)
 ⨯ /Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/rc-input/es/utils/commonUtils.js:1
export function hasAddon(props) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at rc-input/es/utils/commonUtils (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/pages/web3.js:604:18)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/Input.js:12:87)
    at ./node_modules/antd/es/input/Input.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1040:1)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/TextArea.js:20:64)
    at ./node_modules/antd/es/input/TextArea.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1050:1) {
  page: '/web3'
}
 ⨯ unhandledRejection: /Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/rc-input/es/utils/commonUtils.js:1
export function hasAddon(props) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at rc-input/es/utils/commonUtils (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/pages/web3.js:604:18)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/Input.js:12:87)
    at ./node_modules/antd/es/input/Input.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1040:1)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/TextArea.js:20:64)
    at ./node_modules/antd/es/input/TextArea.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1050:1)
 ⨯ unhandledRejection: /Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/rc-input/es/utils/commonUtils.js:1
export function hasAddon(props) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at rc-input/es/utils/commonUtils (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/pages/web3.js:604:18)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/Input.js:12:87)
    at ./node_modules/antd/es/input/Input.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1040:1)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/TextArea.js:20:64)
    at ./node_modules/antd/es/input/TextArea.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1050:1)
/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/rc-input/es/utils/commonUtils.js:1
export function hasAddon(props) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at rc-input/es/utils/commonUtils (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/pages/web3.js:604:18)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/Input.js:12:87)
    at ./node_modules/antd/es/input/Input.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1040:1)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/TextArea.js:20:64)
    at ./node_modules/antd/es/input/TextArea.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1050:1)
/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/rc-input/es/utils/commonUtils.js:1
export function hasAddon(props) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at rc-input/es/utils/commonUtils (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/pages/web3.js:604:18)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/Input.js:12:87)
    at ./node_modules/antd/es/input/Input.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1040:1)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/TextArea.js:20:64)
    at ./node_modules/antd/es/input/TextArea.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1050:1)
 ⨯ unhandledRejection: /Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/rc-input/es/utils/commonUtils.js:1
export function hasAddon(props) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at rc-input/es/utils/commonUtils (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/pages/web3.js:604:18)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/Input.js:12:87)
    at ./node_modules/antd/es/input/Input.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1040:1)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/TextArea.js:20:64)
    at ./node_modules/antd/es/input/TextArea.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1050:1)
 ⨯ unhandledRejection: /Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/rc-input/es/utils/commonUtils.js:1
export function hasAddon(props) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/Users/fengge/Documents/coding/ant-desion-web3-demo/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at rc-input/es/utils/commonUtils (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/pages/web3.js:604:18)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/Input.js:12:87)
    at ./node_modules/antd/es/input/Input.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1040:1)
    at __webpack_require__ (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/antd/es/input/TextArea.js:20:64)
    at ./node_modules/antd/es/input/TextArea.js (/Users/fengge/Documents/coding/ant-desion-web3-demo/.next/server/vendor-chunks/antd.js:1050:1)
 ○ Compiling /_error ...
 ✓ Compiled /_error in 5.6s (6605 modules)

**Comment by gin-lsl** [comment]
看起来你需要将 `rc-input` 也添加到 `transpilePackages` 当中

**Comment by SilenceRichard** [comment]
> 看起来你需要将 `rc-input` 也添加到 `transpilePackages` 当中
添加配置后好使了，可能这跟antd版本有关，在官网的示例配置里是否也需要限制一下antd版本https://web3.ant.design/course/dev-init-cn
<img width="834" alt="image" src="https://github.com/user-attachments/assets/14ebab59-434a-4be0-b0bf-8ebfab258e10">
